apiVersion: v1
kind: ConfigMap
metadata:
  name: internx-config
  namespace: internx
data:
  SPRING_PROFILES_ACTIVE: "prod"
  EUREKA_HOST: "eureka-server.internx.svc.cluster.local"
  DB_HOST: "postgres-service.internx.svc.cluster.local"
  REDIS_HOST: "redis-service.internx.svc.cluster.local"
  KAFKA_SERVERS: "kafka-service.internx.svc.cluster.local:9092"
