apiVersion: v1
kind: Secret
metadata:
  name: internx-secrets
  namespace: internx
type: Opaque
stringData:
  DB_PASSWORD: "secure-cluster-postgres-password-2026"
  JWT_SECRET: "internx-super-secret-jwt-signing-key-for-microservices-2026-production-ready!"
  SENDGRID_API_KEY: "SG.internx-production-key-example"
  GOOGLE_CLIENT_ID: "" # Populate with your Google Cloud Console OAuth 2.0 Client ID
